export const URL =  "";
export const ADD_BREADCRUMB = 'ADD_BREADCRUMB';
export const ADD_BASIC_INFORMATION = 'ADD_BASIC_INFORMATION';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_ACCOUNT_SET_UP = 'ADD_ACCOUNT_SETUP';
export const ADD_PARTICULAR = 'ADD_PARTICULAR';
export const ADD_EXTRA_FITTING = 'ADD_EXTRA_FITTING';
export const ADD_OTHER_INSURANCE = 'ADD_OTHER_INSURANCE';
export const ADD_ACCIDENT_BEFORE = 'ADD_ACCIDENT_BEFORE';
export const ADD_ADDITIONAL_INFO = 'ADD_ADDITIONAL_INFO';
export const ADD_DATE_APPOINTMENT = 'ADD_DATE_APPOINTMENT';
export const ADD_USER_TYPE = 'ADD_USER_TYPE';

